[package]
name = "ustring"
version = "0.1.0"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
spin = "0.5.2"
libc = "0.2.62"
fasthash = "0.4.0"

[dev-dependencies]
criterion="0.2"
crossbeam-utils = "0.6.6"

[[bench]]
name="creation"
harness=false
