[package]
name = "ustr"
version = "0.6.0"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"
license = "BSD-2-Clause-Patent"
description = "Fast, FFI-friendly string interning."
documentation = "https://docs.rs/ustr/0.6.0/ustr/"
repository = "https://github.com/anderslanglands/ustr"
readme = "README.md"
keywords = ["string", "interning", "FFI"]
categories = ["caching", "data-structures"]

[badges]
travis-ci = {repository = "anderslanglands/ustr", branch="master"}

[dependencies]
lazy_static = "1.4.0"
spin = {version = "0.5.2", optional = true }
fasthash = {version = "0.4.0", optional=true}
byteorder = "1.3.2"
serde = {version="1.0", optional=true}
parking_lot = {version = "0.10", optional = true}
ahash = { version = "0.3"}

[dev-dependencies]
criterion="0.2"
crossbeam-utils = "0.6.6"
crossbeam-channel = "0.3.9"
string-interner = "0.7.1"
string_cache = "0.7.3"
libc = "0.2.62"
serde_json = "1.0"

[[bench]]
name="creation"
harness=false

[features]
default = ["parkinglot"]
serialization=["serde"]
spinlock = ["spin"]
parkinglot = ["parking_lot"]
hashcity = ["fasthash"]
