[package]
name = "ustr"
version = "0.1.0"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"
license = "BSD-2-Clause-Patent"
description = "Fast, FFI-friendly string interning."

[dependencies]
lazy_static = "1.4.0"
spin = "0.5.2"
fasthash = "0.4.0"
byteorder = "1.3.2"

[dev-dependencies]
criterion="0.2"
crossbeam-utils = "0.6.6"
crossbeam-channel = "0.3.9"
string-interner = "0.7.1"
string_cache = "0.7.3"
libc = "0.2.62"

[[bench]]
name="creation"
harness=false
